function newString = convert2html(string)
convertTable = {...
'&#33;',' ','%21','!','Exclamation mark';...
'&#34;','&quot;','%22','"','Quotation mark';...
'&#35;',' ','%23','#','Number sign';...
'&#36;',' ','%24','$','Dollar sign';...
'&#37;',' ','%25','%','Percent sign';...
'&#38;','&amp;','%26','&','Ampersand';...
'&#39;',' ','%27','''','Apostrophe';...
'&#40;',' ','%28','(','Left parenthesis';...
'&#41;',' ','%29',')','Right parenthesis';...
'&#42;',' ','%2A','*', 'Asterisk';...
'&#43;',' ','%2B','+','Plus sign';...
'&#44;',' ','%2C',',','Comma';...
'&#45;',' ','%2D','-','Hyphen';...
'&#46;',' ','%2E','.','Period (fullstop)';...
'&#47;',' ','%2F','/','Solidus (slash)';...
'&#58;',' ','%3A',':','Colon';...
'&#59;',' ','%3B',';','Semi-colon';...
'&#60;','&lt;','%3C','<','Less than';...
'&#61;',' ','%3D','=','Equals sign';...
'&#62;','&gt;','%3E','>','Greater than';...
'&#63;',' ','%3F','?','Question mark';...
'&#64;',' ','%40','@','Commercial at';...
'&#91;',' ','%5B','[','Left square bracket';...
'&#92;',' ','%5C','\','Reverse solidus (backslash)';...
'&#93;',' ','%5D',']','Right square bracket';...
'&#94;',' ','%5E','^','Caret';...
'&#95;',' ','%5F','_','Horizontal bar (underscore)';...
'&#96;',' ','%60','`','Acute accent';...
'&#123;',' ','%7B','{','Left curly brace';...
'&#124;',' ','%7C','|','Vertical bar';...
'&#125;',' ','%7D','}','Right curly brace';...
'&#126;',' ','%7E','~','Tilde';...
'&#161;','&iexcl;','%A1','¡','Inverted exclamation';...
'&#162;','&cent;','%A2','¢','Cent sign';...
'&#163;','&pound;','%A3','£','Pound sterling';...
'&#164;','&curren;','%A4','¤','General currency sign';...
'&#165;','&yen;','%A5','¥','Yen sign';...
'&#166;','&brvbar;','%A6','¦','Broken vertical bar';...
'&#167;','&sect;','%A7','§','Section sign';...
'&#168;','&uml;','%A8','¨','Umlaut (dieresis)';...
'&#169;','&copy;','%A9','©','Copyright';...
'&#170;','&ordf;','%AA','ª','Feminine ordinal';...
'&#171;','&laquo;','%AB','«','Left angle quote, guillemotleft';...
'&#172;','&not;','%AC','¬','Not sign';...
'&#173;','&shy;','%AD','','Soft hyphen';...
'&#174;','&reg;','%AE','®','Registered trademark';...
'&#175;','&macr;','%AF','¯','Macron accent';...
'&#176;','&deg;','%B0','°','Degree sign';...
'&#177;','&plusmn;','%B1','±','Plus or minus';...
'&#178;','&sup2;','%B2','²','Superscript two';...
'&#179;','&sup3;','%B3','³','Superscript three';...
'&#180;','&acute;','%B4','´','Acute accent';...
'&#181;','&micro;','%B5','µ','Micro sign';...
'&#182;','&para;','%B6','¶','Paragraph sign';...
'&#183;','&middot;','%B7','·','Middle dot';...
'&#184;','&cedil;','%B8','¸','Cedilla';...
'&#185;','&sup1;','%B9','¹','Superscript one';...
'&#186;','&ordm;','%BA','º','Masculine ordinal';...
'&#187;','&raquo;','%BB','»','Right angle quote, guillemotright';...
'&#188;','&frac14;','%BC','¼','Fraction one-fourth';...
'&#189;','&frac12;','%BD','½','Fraction one-half';...
'&#190;','&frac34;','%BE','¾','Fraction three-fourths';...
'&#191;','&iquest;','%BF','¿','Inverted question mark';...
'&#192;','&Agrave;','%C0','À','Capital A, grave accent';...
'&#193;','&Aacute;','%C1','Á','Capital A, acute accent';...
'&#194;','&Acirc;','%C2','Â','Capital A, circumflex accent';...
'&#195;','&Atilde;','%C3','Ã','Capital A, tilde';...
'&#196;','&Auml;','%C4','Ä','Capital A, dieresis or umlaut mark';...
'&#197;','&Aring;','%C5','Å','Capital A, ring';...
'&#198;','&AElig;','%C6','Æ','Capital AE dipthong (ligature)';...
'&#199;','&Ccedil;','%C7','Ç','Capital C, cedilla';...
'&#200;','&Egrave;','%C8','È','Capital E, grave accent';...
'&#201;','&Eacute;','%C9','É','Capital E, acute accent';...
'&#202;','&Ecirc;','%CA','Ê','Capital E, circumflex accent';...
'&#203;','&Euml;','%CB','Ë','Capital E, dieresis or umlaut mark';...
'&#204;','&Igrave;','%CC','Ì','Capital I, grave accent';...
'&#205;','&Iacute;','%CD','Í','Capital I, acute accent';...
'&#206;','&Icirc;','%CE','Î','Capital I, circumflex accent';...
'&#207;','&Iuml;','%CF','Ï','Capital I, dieresis or umlaut mark';...
'&#208;','&ETH;','%D0','Ð','Capital Eth, Icelandic';...
'&#209;','&Ntilde;','%D1','Ñ','Capital N, tilde';...
'&#210;','&Ograve;','%D2','Ò','Capital O, grave accent';...
'&#211;','&Oacute;','%D3','Ó','Capital O, acute accent';...
'&#212;','&Ocirc;','%D4','Ô','Capital O, circumflex accent';...
'&#213;','&Otilde;','%D5','Õ','Capital O, tilde';...
'&#214;','&Ouml;','%D6','Ö','Capital O, dieresis or umlaut mark';...
'&#215;','&times;','%D7','×','Multiply sign';...
'&#216;','&Oslash;','%D8','Ø','Capital O, slash';...
'&#217;','&Ugrave;','%D9','Ù','Capital U, grave accent';...
'&#218;','&Uacute;','%DA','Ú','Capital U, acute accent';...
'&#219;','&Ucirc;','%DB','Û','Capital U, circumflex accent';...
'&#220;','&Uuml;','%DC','Ü','Capital U, dieresis or umlaut mark';...
'&#221;','&Yacute;','%DD','Ý','Capital Y, acute accent';...
'&#222;','&THORN;','%DE','Þ','Capital THORN, Icelandic';...
'&#223;','&szlig;','%DF','ß','Small sharp s, German (sz ligature)';...
'&#224;','&agrave;','%E0','à','Small a, grave accent';...
'&#225;','&aacute;','%E1','á','Small a, acute accent';...
'&#226;','&acirc;','%E2','â','Small a, circumflex accent';...
'&#227;','&atilde;','%E3','ã','Small a, tilde';...
'&#228;','&auml;','%E4','ä','Small a, dieresis or umlaut mark';...
'&#229;','&aring;','%E5','å','Small a, ring';...
'&#230;','&aelig;','%E6','æ','Small ae dipthong (ligature)';...
'&#231;','&ccedil;','%E7','ç','Small c, cedilla';...
'&#232;','&egrave;','%E8','è','Small e, grave accent';...
'&#233;','&eacute;','%E9','é','Small e, acute accent';...
'&#234;','&ecirc;','%EA','ê','Small e, circumflex accent';...
'&#235;','&euml;','%EB','ë','Small e, dieresis or umlaut mark';...
'&#236;','&igrave;','%EC','ì','Small i, grave accent';...
'&#237;','&iacute;','%ED','í','Small i, acute accent';...
'&#238;','&icirc;','%EE','î','Small i, circumflex accent';...
'&#239;','&iuml;','%EF','ï','Small i, dieresis or umlaut mark';...
'&#240;','&eth;','%F0','ð','Small eth, Icelandic';...
'&#241;','&ntilde;','%F1','ñ','Small n, tilde';...
'&#242;','&ograve;','%F2','ò','Small o, grave accent';...
'&#243;','&oacute;','%F3','ó','Small o, acute accent';...
'&#244;','&ocirc;','%F4','ô','Small o, circumflex accent';...
'&#245;','&otilde;','%F5','õ','Small o, tilde';...
'&#246;','&ouml;','%F6','ö','Small o, dieresis or umlaut mark';...
'&#247;','&divide;','%F7','÷','Division sign';...
'&#248;','&oslash;','%F8','ø','Small o, slash';...
'&#249;','&ugrave;','%F9','ù','Small u, grave accent';...
'&#250;','&uacute;','%FA','ú','Small u, acute accent';...
'&#251;','&ucirc;','%FB','û','Small u, circumflex accent';...
'&#252;','&uuml;','%FC','ü','Small u, dieresis or umlaut mark';...
'&#253;','&yacute;','%FD','ý','Small y, acute accent';...
'&#254;','&thorn;','%FE','þ','Small thorn, Icelandic';...
'&#255;','&yuml;','%FF','ÿ','Small y, dieresis or umlaut mark';...
};
newString = [];
for c = 1:length(string)
    [bool index] = ismember(string(c),convertTable(:,4));
    if bool
        newString = [newString convertTable{index,3}];
    else
        newString = [newString string(c)];
    end
end
